# Workflow for building and testing the server

name: Server CI

on:
  push:
    branches: [ "master" ]
    paths:
      - server/**
      - .github/workflows/server.yml
  pull_request:
    branches: [ "master" ]
    paths:
      - server/**
      - .github/workflows/server.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.x

    - name: Build
      working-directory: ./server
      run: go build -v ./...

    - name: Test
      working-directory: ./server
      run: go test -v ./...